const languages = [
    { code: "af", name: "Afrikaans"},
    { code: "am", name: "Amharic"},
    { code: "ar", name: "Arabic"},
    { code: "bg", name: "Bulgarian"},
    { code: "bn", name: "Bengali"},
    { code: "bs", name: "Bosnian"},
    { code: "ca", name: "Catalan"},
    { code: "cs", name: "Czech"},
    { code: "da", name: "Danish"},
    { code: "de", name: "German"},
    { code: "el", name: "Greek"},
    { code: "en", name: "English"},
    { code: "es", name: "Spanish"},
    { code: "et", name: "Estonian" },
    { code: "eu", name: "Basque" },
    { code: "fi", name: "Finnish" },
    { code: "fr", name: "French" },
    { code: "gl", name: "Galician" },
    { code: "gu", name: "Gujarati" },
    { code: "hi", name: "Hindi" },
    { code: "hr", name: "Croatian" },
    { code: "hu", name: "Hungarian" },
    { code: "hy", name: "Armenian" },
    { code: "id", name: "Indonesian" },
    { code: "is", name: "Icelandic" },
    { code: "it", name: "Italian" },
    { code: "iw", name: "Hebrew" },
    { code: "ja", name: "Japanese"},
    { code: "jv", name: "Javanese" },
    { code: "ka", name: "Georgian" },
    { code: "kk", name: "Kazakh" },
    { code: "km", name: "Khmer" },
    { code: "kn", name: "Kannada" },
    { code: "ko", name: "Korean" },
    { code: "lo", name: "Laos" },
    { code: "sl", name: "Slovenian" },
    { code: "lv", name: "Latvian" },
    { code: "mk", name: "Macedonian" },
    { code: "ml", name: "Malayalam" },
    { code: "mn", name: "Mongolian" },
    { code: "mr", name: "Marathi" },
    { code: "ms", name: "Malay" },
    { code: "my", name: "Burmese" },
    { code: "ne", name: "Nepali (India)" },
    { code: "nl", name: "Dutch" },
    { code: "no", name: "Norwegian" },
    { code: "pa", name: "Punjabi" },
    { code: "pl", name: "Polish" },
    { code: "pt", name: "Portuguese" },
    { code: "ro", name: "Romanian" },
    { code: "ru", name: "Russian" },
    { code: "rw", name: "Kinyarwanda" },
    { code: "sk", name: "Slovak" },
    { code: "sq", name: "Albanian" },
    { code: "sr", name: "Serbian" },
    { code: "su", name: "Sundanese" },
    { code: "sv", name: "Swedish" },
    { code: "sw", name: "Swahili" },
    { code: "ta", name: "Tamil" },
    { code: "te", name: "Telugu" },
    { code: "th", name: "Thai" },
    { code: "tn", name: "Tswana" },
    { code: "tr", name: "Turkish" },
    { code: "ts", name: "Tsonga" },
    { code: "uk", name: "Ukrainian" },
    { code: "ur", name: "Urdu" },
    { code: "uz", name: "Uzbek" },
    { code: "ve", name: "Venda" },
    { code: "vi", name: "Vietnamese" },
    { code: "xh", name: "Xhosa" },
    { code: "cmn", name: "Chinese" },
    { code: "zu", name: "Zulu" }
];

export default languages;